DROP TABLE [dbo].[Competitor]
DROP TABLE [dbo].[Match]
DROP TABLE [dbo].[Tournament]
DROP TABLE [dbo].[Event]
DROP INDEX [IX_RoleId] ON [dbo].[AspNetUserRoles]
DROP INDEX [IX_UserId] ON [dbo].[AspNetUserRoles]
DROP TABLE [dbo].[AspNetUserRoles]
DROP INDEX [IX_UserId] ON [dbo].[AspNetUserLogins]
DROP TABLE [dbo].[AspNetUserLogins]
DROP INDEX [IX_UserId] ON [dbo].[AspNetUserClaims]
DROP TABLE [dbo].[AspNetUserClaims]
DROP INDEX [UserNameIndex] ON [dbo].[AspNetUsers]
DROP TABLE [dbo].[AspNetUsers]
DROP INDEX [RoleNameIndex] ON [dbo].[AspNetRoles]
DROP TABLE [dbo].[AspNetRoles]